#!/usr/bin/env python

import urllib2
import sys
import os

try:
    import json
except ImportError:
    import simplejson as json

id = "localhsot"

def getNodes():
    host = os.environ.get("host", "127.0.0.1")
    port = 9200
    name = '%s' % os.uname()[1]
    url = "http://%s:%d/_nodes/%s" % (host, port, name)
    if os.environ['serial_id']:
        serial_id = os.environ['serial_id']
    req = urllib2.Request(url)
    raw = urllib2.urlopen(req).read()
    return json.loads( raw )['nodes'][serial_id]

heap_init = "heap_init"
heap_max = "heap_max"
non_heap_init = "non_heap_init"
non_heap_max = "non_heap_max"
direct_max = "direct_max"

def doData():
    print heap_init + ".value " + str( getNodes()["jvm"]["mem"]["heap_init_in_bytes"] )
    print heap_max + ".value " + str( getNodes()["jvm"]["mem"]["heap_max_in_bytes"] )
    print non_heap_init + ".value " + str( getNodes()["jvm"]["mem"]["non_heap_init_in_bytes"] )
    print non_heap_max + ".value " + str( getNodes()["jvm"]["mem"]["non_heap_max_in_bytes"] )
    print direct_max + ".value " + str( getNodes()["jvm"]["mem"]["direct_max_in_bytes"] )


def doConfig():

    print "graph_title elasticsearch node heap"
    print "graph_args --base 1000 -l 0 "
    print "graph_vlabel Bytes"
    print "graph_category elasticsearch nodes"

    print heap_init + ".label " + heap_init
    print heap_max + ".label " + heap_max
    print non_heap_init + ".label " + non_heap_init
    print non_heap_max + ".label " + non_heap_max
    print direct_max + ".label " + direct_max

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "config":
        doConfig()
    else:
        doData()
