#!/usr/bin/env python

import urllib2
import sys
import os

try:
    import json
except ImportError:
    import simplejson as json

id = "localhsot"

def getNodes():
    host = os.environ.get("host", "127.0.0.1")
    port = 9200
    name = '%s' % os.uname()[1]
    url = "http://%s:%d/_nodes/%s" % (host, port, name)
    if os.environ['serial_id']:
        serial_id = os.environ['serial_id']
    req = urllib2.Request(url)
    raw = urllib2.urlopen(req).read()
    return json.loads( raw )['nodes'][serial_id]

min = "min"
max = "max"

def doData():
    print min + ".value " + str( getNodes()["thread_pool"]["flush"]["min"] )
    print max + ".value " + str( getNodes()["thread_pool"]["flush"]["max"] )


def doConfig():

    print "graph_title elasticsearch node thread_pool flush"
    print "graph_args --base 1000 -l 0 "
    print "graph_vlabel queue sizes"
    print "graph_category elasticsearch_nodes"

    print min + ".label " + min
    print max + ".label " + max

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "config":
        doConfig()
    else:
        doData()

