#!/usr/bin/env python

import urllib2
import sys
import os

try:
    import json
except ImportError:
    import simplejson as json

def getNodes():
    host = os.environ.get("host", "127.0.0.1")
    port = 9200
    name = '%s' % os.uname()[1]
    url = "http://{0}:{1}/_nodes/{2}".format(host, port, name)
    req = urllib2.Request(url)
    raw = urllib2.urlopen(req).read()
    jsonData = json.loads( raw )['nodes']
    keyList = jsonData.keys()
    return jsonData[keyList[0]] 

min = "min"
max = "max"

def doData():
    print min + ".value " + str( getNodes()["thread_pool"]["refresh"]["min"] )
    print max + ".value " + str( getNodes()["thread_pool"]["refresh"]["max"] )


def doConfig():

    print "graph_title elasticsearch node thread_pool refresh"
    print "graph_args --base 1000 -l 0 "
    print "graph_vlabel queue sizes"
    print "graph_category elasticsearch_nodes"

    print min + ".label " + min
    print max + ".label " + max

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "config":
        doConfig()
    else:
        doData()
