#!/usr/bin/env python

import urllib2
import sys
import os

try:
    import json
except ImportError:
    import simplejson as json


def getNodes():
    host = os.environ.get("host", "127.0.0.1")
    port = 9200
    url = "http://%s:%d/_cluster/stats" % (host, port)
    req = urllib2.Request(url)
    raw = urllib2.urlopen(req).read()
    return json.loads( raw )["nodes"]

threads = "threads"

def doData():
    print threads + ".value " + str( getNodes()["jvm"]["threads"] )

def doConfig():

    print "graph_title elasticsearch cluster thread"
    print "graph_args --base 1000 -l 0 "
    print "graph_vlabel thread"
    print "graph_category elasticsearch_cluster"

    print threads + ".label " + threads



if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "config":
        doConfig()
    else:
        doData()
